### ISSUE TITLE
reproduce .DS_Store file creation

### ISSUE THREAD

**Issue by MareoRaft** [snielsen/DeathToDSStore#8]
What is an easy situation where we know that MacOS will try to create a .DS_Store file?

(This is helpful for debugging)

**Comment by snielsen** [comment]
Sorry for taking so long to reply. Unfortunately the Finder is a little opaque when it comes to knowing when it will try to flush DS_Store info to the filesystem. 

Often I have found that doing pretty much anything like changing a file label, resizing the window or modifying icon placement will usually do the trick.
